import piggyphoto
import ctypes
C = piggyphoto.camera()
print("***************** CAMERA ABILITIES **************")
print C.abilities
print("*************************************************")
C.trigger_capture_image()
#print C.config.main.imgsettings.iso
#x=C.get_widget('main.capturesettings.shutterspeed')
#print(x)

#c_w=C.config.get_child_by_name('shutterspeed')
#c_w._set_value('1/1000')
#C.set_single_config('shutterspeed',c_w)

#c_w=C.config.get_child_by_name('iso')
#c_w._set_value('5000')
#C.set_single_config('iso',c_w)

#c_w=C.config.get_child_by_name('f-number')
#c_w._set_value(2.5)
#C.set_single_config('f-number',c_w)
#print(C.list_config())

#win=C._get_config()
#shutter_wid=win.get_child_by_name('shutterspeed')
#shutter_wid._set_value('1/2000')
#iso_wid=win.get_child_by_name('iso')
#iso_wid._set_value('5000')
#C._set_config(win)

#print('%%%%%%%%%%%%%%%%%')
#print(C._get_config()._w)
#print(C._get_config()._w)
#print(C._get_config()._w)
#print(C._get_config()._w)
#print('%%%%%%%%%%%%%%%%%')
#print('$$$$$$$$$$$$$$$$$')
#c_w=C.config.get_child_by_name('shutterspeed')
#print(c_w._w)
#c_w=C.config.get_child_by_name('shutterspeed')
#print(c_w._w)
#c_w=C.config.get_child_by_name('shutterspeed')
#print(c_w._w)
#print('$$$$$$$$$$$$$$$$$')
#print('**********')
#c_w._set_value('1/1000')
#c_w._set_changed(1)
#C.set_single_config('shutterspeed',c_w)
#C._set_config(C._get_config())
#print(c_w)
#c_w=C.config.get_child_by_name('shutterspeed')
#print(c_w._w)
#print(c_w)
#print('**********')

#C._set_config(C.config)
#C.set_single_config('shutterspeed',c_w)
#win=C._get_config()
#print(win)
#print(c_w)
#c_w._set_value('1/1000')
#C.set_single_config('shutterspeed',c_w)
#print(c_w)
#win=C._get_config()
#C._set_config(win)
#C.list_config()


#print(c_w)
#C.set_single_config('shutterspeed',c_w)

#c_w=piggyphoto.cameraWidget(label='main.capturesettings.shutterspeed')
#print(c_w._get_name())
#C.capture_preview('preview.jpg')
#C.capture_image('image.jpg')
